[workspace]
members = [
  "crates/rito-core",
  "crates/rito-ffi",
  "crates/rito-block",
  "crates/rito-fragment",
  "crates/rito-inline",
  "crates/rito-source",
  "crates/rito-style-contract",
  "crates/rito-stylo",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/Ringyuki/Rito"
rust-version = "1.95"
version = "0.0.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[patch.crates-io]
parley = { path = "crates/vendor/parley" }
